-- 博客数据库初始化脚本 v1.0.0

CREATE DATABASE IF NOT EXISTS blog CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE blog;

-- 用户表
CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME,
    git_hub_id BIGINT UNSIGNED NOT NULL UNIQUE COMMENT 'GitHub用户ID',
    login VARCHAR(255) COMMENT 'GitHub登录名',
    name VARCHAR(255) COMMENT '显示名称',
    avatar_url VARCHAR(512) COMMENT '头像URL',
    email VARCHAR(255) COMMENT '邮箱'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 文章表
CREATE TABLE IF NOT EXISTS posts (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME,
    slug VARCHAR(255) NOT NULL UNIQUE COMMENT '文章URL slug',
    title VARCHAR(255) COMMENT '文章标题',
    date DATETIME COMMENT '发布日期',
    tags TEXT COMMENT '标签，逗号分隔',
    categories TEXT COMMENT '分类，逗号分隔',
    summary TEXT COMMENT '摘要',
    content LONGTEXT COMMENT 'HTML内容',
    views BIGINT UNSIGNED DEFAULT 0 COMMENT '阅读量'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 访问记录表
CREATE TABLE IF NOT EXISTS visits (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME,
    post_slug VARCHAR(255) COMMENT '文章slug',
    user_id BIGINT COMMENT '用户ID',
    ip VARCHAR(50) COMMENT 'IP地址',
    user_agent VARCHAR(500) COMMENT 'UA'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 索引
CREATE INDEX idx_posts_date ON posts(date DESC);
CREATE INDEX idx_posts_slug ON posts(slug);
CREATE INDEX idx_visits_post_slug ON visits(post_slug);
